ALTER TABLE user
MODIFY COLUMN firstname CHAR(50) CHARACTER SET UTF8MB4,
MODIFY COLUMN lastname CHAR(50) CHARACTER SET UTF8MB4;

ALTER TABLE product
MODIFY COLUMN name CHAR(50) CHARACTER SET UTF8MB4;

ALTER TABLE user_audit
MODIFY COLUMN firstname CHAR(255) CHARACTER SET UTF8MB4,
MODIFY COLUMN lastname CHAR(255) CHARACTER SET UTF8MB4;

ALTER TABLE product_audit
MODIFY COLUMN name CHAR(255) CHARACTER SET UTF8MB4;

ALTER TABLE address
MODIFY COLUMN city CHAR(50) CHARACTER SET UTF8MB4,
MODIFY COLUMN street CHAR(50) CHARACTER SET UTF8MB4;

ALTER TABLE address_audit
MODIFY COLUMN city CHAR(50) CHARACTER SET UTF8MB4,
MODIFY COLUMN street CHAR(50) CHARACTER SET UTF8MB4;

ALTER TABLE supplier
MODIFY COLUMN company_name CHAR(75) CHARACTER SET UTF8MB4;

ALTER TABLE supplier_audit
MODIFY COLUMN company_name CHAR(75) CHARACTER SET UTF8MB4;